### ISSUE TITLE
PDF Invoices does not work with NGINX

### ISSUE THREAD

**Issue by huwgit** [Pinelab-studio/pinelab-vendure-plugins#98] opened 2023-02-09 13:25 UTC
**Which plugin is the issue about?**
PDF Invoices

**Describe the bug**
NGINX advice needed in set up for pinelab PDF Invoices Plugin. The plugin works fine without NGINX. I have my Remix storefront on port 3001, my vendure server on port 3000. NGINX listens on port 80 and routes / to 3001 and /admin to 3000. 

**To Reproduce**
1. Install NGINX (listens on port 80) and route the vendure admin to port 3000. Route Remix Storefront to port 3001. 
2. Install @vendure/ui-devkit
3. Install Invoices Plugin following instructions here --- https://pinelab-plugins.com/plugin/vendure-plugin-invoices
4. Update vendure-config.ts

The **orders are not listing inside the invoices**. Aslo when I click PREVIEW I get an error Unexpected token **'</' 'Doctyper is not valid JSON**. I changed the template to a simple html file and got the same error.

**Expected behavior**
The orders to list and the preview to open a PDF preview.

**Screenshots**
<img width="452" alt="Screenshot 2023-02-07 at 10 26 11" src="https://user-images.githubusercontent.com/9348884/217824551-29c0f222-dbe1-4acc-992c-464bf75a2934.png">
**Environment**

Node v16.15.1
Npm 9.1.2
@vendure/create v1.8.5!

**Comment by thijmenogerion** [comment] 2023-02-09 18:03
maybe share vendure-config.ts plugin config and nginx config ?

**Comment by huwgit** [comment] 2023-02-09 23:06
server {



  server_name abnstone.co.uk www.abnstone.co.uk;



  location / {

    proxy_pass http://localhost:3001;

    proxy_http_version 1.1;

    proxy_set_header Upgrade $http_upgrade;

    proxy_set_header Connection 'upgrade';

    proxy_set_header Host $host;

    proxy_cache_bypass $http_upgrade;

  }
  location /admin {

    proxy_pass http://localhost:3000;

    proxy_http_version 1.1;

    proxy_set_header Upgrade $http_upgrade;

    proxy_set_header Connection 'upgrade';

    proxy_set_header Host $host;

    proxy_cache_bypass $http_upgrade;

  }
location /assets {

    proxy_pass http://localhost:3000;

    proxy_http_version 1.1;

    proxy_set_header Upgrade $http_upgrade;

    proxy_set_header Connection 'upgrade';

    proxy_set_header Host $host;

    proxy_cache_bypass $http_upgrade;

  }
  location /shop-api {

    proxy_pass http://localhost:3000;

    proxy_http_version 1.1;

    proxy_set_header Upgrade $http_upgrade;

    proxy_set_header Connection 'upgrade';

    proxy_set_header Host $host;

    proxy_cache_bypass $http_upgrade;

  }
 location /health {

    proxy_pass http://localhost:3000;

    proxy_http_version 1.1;

    proxy_set_header Upgrade $http_upgrade;

    proxy_set_header Connection 'upgrade';

    proxy_set_header Host $host;

    proxy_cache_bypass $http_upgrade;

  }


    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/abnstone.co.uk/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/abnstone.co.uk/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.abnstone.co.uk) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = abnstone.co.uk) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



  listen 80;

  listen [::]:80;



  server_name abnstone.co.uk www.abnstone.co.uk;
    return 404; # managed by Certbot

                                                                                       }

**Comment by huwgit** [comment] 2023-02-09 23:09
relevant parts in vendure config

import { StripePlugin } from '@vendure/payments-plugin/package/stripe';
import { compileUiExtensions } from '@vendure/ui-devkit/compiler';

...

 InvoicePlugin.init({
    /**
     * This plugins requires a license for commercial use.
     * Visit https://pinelab-plugins.com/vendure-plugin-invoices
     * for more information
     */
     licenseKey: String(process.env.PINELAB_LICENSE),
    // Used for generating download URLS for the admin ui
//    vendureHost: 'https://abnstone.co.uk/admin',
     vendureHost: 'https://abnstone.co.uk/invoices',
  }),
  // Add the invoices page to the admin ui
  AdminUiPlugin.init({
    port: 3002,
    route: 'admin',
    app: compileUiExtensions({
      outputPath: path.join(__dirname, '../admin-ui'),
      extensions: [InvoicePlugin.ui],
    }),
  }),

**Comment by thijmenogerion** [comment] 2023-02-10 06:21
I see two things you can try:
1. add location /invoices to nginx configuration to vendure backend  (:3000?)
2. change vendureHost in InvoicePlugin to only the host (https://abnstone.co.uk)

**Comment by martijnvdbrug** [comment] 2023-02-10 07:54
Hi Huw, thank you for your bug report.

You indicated that the plugin is working as expected on your test environment with the same settings, but not on your production environment, and the only difference was that you used NGINX on your prod env? To me this indicates that the issue is not with the plugin, but rather with your NGINX settings. (I unfortunately have very little experience with NGINX)

What @thijmenogerion said in 2 is correct: you should only set the host in the invoice settings, but that misconfiguration shouldn't cause invoices not being generated. The host is only used to construct download url's for customers, invoices should still be generated.

I suggest to try suggestion 1 from @thijmenogerion, because the preview calls `/invoices/preview` on the vendure server, and I don't see that in your NGINX config anywhere.

Would it be possible to recreate your test env the same as your prod env, so I can have a look?

**Comment by huwgit** [comment] 2023-02-10 09:53
Some success but no download - I did option 1 and 2 above and the invoices have started listing. If I click preview or download buttons I get the error as described in my first post (unexpected token). Clicking the downlad arrow button on the right I get bad gateway (nginx error)...

![image](https://user-images.githubusercontent.com/9348884/218060711-9624d8b7-1a7d-47ac-a1d2-e03ac36ee2b0.png)

**Comment by martijnvdbrug** [comment] 2023-02-13 12:18
@huwgit Good that you got the invoice generation working. 
Make sure that `/invoices` going to the Vendure server in your NGINX config. The URL seems to be correct. Maybe good to know for your NGINX config: `/invoices/90jkjks/ordercode?email=bla@test.com` redirects to another URL, where the actual file is located.

I am closing this issue as it's not related to the plugin.

**Closed by martijnvdbrug** 2023-02-13 12:18 UTC
