### ISSUE TITLE
vendure-plugin-modify-customer-orders crashes server 

### ISSUE THREAD

**Issue by mschipperheyn** [Pinelab-studio/pinelab-vendure-plugins#340] opened 2024-01-23 13:13 UTC
**Which plugin/repository is the issue about?**
vendure-plugin-modify-customer-orders

**Describe the bug**
I have an issue where  I think, but am not sure, `transitionOrderToState(123, 'ArrangingPayment')` is called twice and ends up changing order state to `active`. For some reason this transition triggers the `OrderTransitionListenerService` twice. Which leads to the order being deleted, since in that scenario `activeOrder` and `draftOrder` are the same. 

This is odd since you would not expect the listener to trigger again when the order state has already transitioned to `ArrangingPayment`. Transaction issue?

**To Reproduce**
I didn't have this issue before and only just starting getting this. It seems to be caused by calling `transitionOrderToState(123, 'ArrangingPayment')` twice. One I'm doing manually and immediately subsequently, Stripe does so as well as it is creating a PaymentIntent.

**Expected behavior**
First of all, no error in the listener should result in a server crash. It is caused by the attempt to retrieve the now deleted order, which throws.

Second, while the order deletion may be reasoned through, it is not a desirable outcome, since it is counter intuitive and has a destructive outcome. I recommend 

- try/catching any possible thrown errors to avoid a server crash
- logging an error if draftOrder and activeOrder have the same id and returning, since this is not a valid action
- should stripe be called a orderStateTransition on an order that already has the desired state? My guess is: no

**Screenshots**

**Environment**

- NodeJS version
- Vendure version: 2.1.6
- Plugin version 1.1.0
- Database Postgres
- Any other version numbers from the environment you're using

**Additional context**

**Comment by martijnvdbrug** [comment] 2024-01-23 15:41
I wasn't able to reproduce this unfortunately, but I have done some improvements that **should** fix this issue:

* Catch errors in listeners to prevent server crash. This should definitely not crash the server indeed. (This arguable should be solved in Vendure core)
* Deactive order instead of deleting in case of already present active order.

Please let me know if this solves your issue, as I'm not able to reproduce it.

https://github.com/Pinelab-studio/pinelab-vendure-plugins/pull/344

**Comment by mschipperheyn** [comment] 2024-01-23 17:13
Great! I will try to reproduce it and let you know if this update solves it

**Comment by martijnvdbrug** [comment] 2024-01-25 13:04
@mschipperheyn Closing for now, feel free to re-open if its not sovled of course

**Closed by martijnvdbrug** 2024-01-25 13:04 UTC
